[env]
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs
build_flags =
    -DCORE_DEBUG_LEVEL=0
build_src_filter = +<*> +<buddies/>
lib_deps =
    m5stack/M5Unified
    m5stack/M5GFX
    bitbank2/AnimatedGIF @ ^2.1.1
    bblanchon/ArduinoJson @ ^7.0.0

[env:m5stack-sticks3]
platform = espressif32
board = esp32-s3-devkitc-1
board_build.partitions = no_ota.csv
board_build.arduino.memory_type = qio_opi
build_flags =
    ${env.build_flags}
    -DBOARD_HAS_PSRAM
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
lib_deps =
    ${env.lib_deps}
    https://github.com/m5stack/M5PM1
